version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - TRANSLATION_API_KEY=your-api-key

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app   # Mounts frontend code
      - /app/node_modules # Prevents conflicts with host node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables file watching inside Docker